server:
  servlet:
    context-path: /client
  port: 9095

spring:
  thymeleaf:
    cache: false

logging:
  level:
    root: info
    org:
      springframework:
        web: info

democlient:
  client-id: demo-client
  redirect-uri: http://localhost:9095/client/callback
  pkce: false
  authorization:
    endpoint: http://localhost:8080/auth/realms/workshop/protocol/openid-connect/auth
    response-type: code
    scope: offline_access
  token:
    endpoint: http://localhost:8080/auth/realms/workshop/protocol/openid-connect/token
    client-secret: b3ec9d3f-d1ee-4a18-b4ba-05d832c15293
  introspection:
    endpoint: http://localhost:8080/auth/realms/workshop/protocol/openid-connect/token/introspect


